server.port=8090
spring.application.name=compatibility-service
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=as
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# Registro en Eureka. spring.application.name (arriba) es el nombre con que queda registrado.
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# CLAVE SECRETA JWT: EXACTAMENTE la misma que en msvc-usuarios y el gateway (para validar la firma).
jwt.secret=dylangoticasJoaquinWatonasMaxiAas2026newINFORMATICgen